package top.yuyanmc.properties;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;

public class PropertiesEditor {
    private File file;
    protected Properties properties;
    public PropertiesEditor(File file){
        this.file=file;
        properties=new Properties();
        try {
            file.createNewFile();
            properties.load(new FileInputStream(file));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    public void writeMinecraftServerDefault(){
        properties.clear();
        edit("allow-flight","false");
        edit("allow-nether","true");
        edit("broadcast-console-to-ops","true");
        edit("broadcast-rcon-to-ops","true");
        edit("difficulty", "easy");
        edit("enable-command-block","false");
        edit("enable-jmx-monitoring","false");
        edit("enable-query","false");
        edit("enable-rcon","false");
        edit("enable-status","true");
        edit("enforce-whitelist","false");
        edit("entity-broadcast-range-percentage","100");
        edit("force-gamemode","false");
        edit("function-permission-level","2");
        edit("gamemode","survival");
        edit("generate-structures","true");
        edit("generator-settings","");
        edit("hardcore","false");
        edit("hide-online-players","false");
        edit("level-name","world");
        edit("level-seed","");
        edit("level-type","default");
        edit("max-build-height","319");
        edit("max-players","20");
        edit("max-tick-time","60000");
        edit("max-world-size","29999984");
        edit("motd","A Minecraft Server");
        edit("network-compression-threshold","256");
        edit("online-mode","true");
        edit("op-permission-level","4");
        edit("player-idle-timeout", "0");
        edit("prevent-proxy-connections","false");
        edit("pvp","true");
        edit("query.port","25565");
        edit("rate-limit","0");
        edit("rcon.password","");
        edit("rcon.port","25575");
        edit("require-resource-pack","false");
        edit("resource-pack","");
        edit("resource-pack-prompt","");
        edit("resource-pack-sha1","");
        edit("server-ip","");
        edit("server-port","25565");
        edit("simulation-distance","10");
        edit("spawn-animals","true");
        edit("spawn-monsters","true");
        edit("spawn-npcs","true");
        edit("spawn-protection","16");
        edit("sync-chunk-writes","true");
        edit("text-filtering-config","");
        edit("use-native-transport","true");
        edit("view-distance","10");
        edit("white-list","false");
        save();
    }
    public void edit(String arg1,String arg2){
        properties.put(arg1,arg2);
    }
    public void edit(String arg1,Object arg2){
        properties.put(arg1,arg2.toString());
    }
    public void putDefault(String arg1,Object arg2){
        if(!properties.containsKey(arg1)){
            edit(arg1,arg2);
        }
    }
    public Object get(String arg1){
        return properties.get(arg1);
    }
    public void save(){
        try {
            properties.store(new FileOutputStream(file,false),"This file is auto created by Misuka Mcsm.\nDo not edit this file unless you know what you are doing.");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
